### ISSUE TITLE
Minor issues getting the scripts to run

### ISSUE THREAD

**Issue by Kevinpgalligan** [nv-tlabs/lift-splat-shoot#2]
Thanks for sharing!

I've come across a few minor issues while running the scripts.

1. tensorboardX was missing as a dependency, I couldn't run the "Visualize Input/Output Data" script without it.
2. "Evaluate a model" - this failed because the default GPU ID is 1 in the script, and I only have 1 GPU. (src/explore.py, eval_model_iou() function). I fixed this by changing the default to 0. There are other functions in this script that also use gpuid=1 as default. I see now that you can set gpuid from the CLI, but 0 might be a saner default.
3. "Visualise predictions" - fails due to a missing file (see below). Perhaps I'm not setting the map_folder parameter correctly, or it presumes that you have the full nuScenes dataset available rather than just the mini version?

```
python main.py viz_model_preds mini --modelf=/home/kevingal/phd/placement/liftsplat-model.pt --dataroot=/home/kevingal/phd/placement/nuscenes/ --map_folder=/home/kevingal/phd/placement/nuscenes/mini/
NuscData: 323 samples. Split: train.
                   Augmentation Conf: {'resize_lim': (0.193, 0.225), 'final_dim': (128, 352), 'rot_lim': (-5.4, 5.4), 'H': 900, 'W': 1600, 'rand_flip': True, 'bot_pct_lim': (0.0, 0.22), 'cams': ['CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT'], 'Ncams': 5}
NuscData: 81 samples. Split: val.
                   Augmentation Conf: {'resize_lim': (0.193, 0.225), 'final_dim': (128, 352), 'rot_lim': (-5.4, 5.4), 'H': 900, 'W': 1600, 'rand_flip': True, 'bot_pct_lim': (0.0, 0.22), 'cams': ['CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_LEFT', 'CAM_BACK', 'CAM_BACK_RIGHT'], 'Ncams': 5}
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    Fire({
  File "/home/kevingal/anaconda3/envs/liftsplat/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/kevingal/anaconda3/envs/liftsplat/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/kevingal/anaconda3/envs/liftsplat/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/kevingal/phd/placement/lift-splat-shoot/src/explore.py", line 293, in viz_model_preds
    nusc_maps = get_nusc_maps(map_folder)
  File "/home/kevingal/phd/placement/lift-splat-shoot/src/tools.py", line 288, in get_nusc_maps
    nusc_maps = {map_name: NuScenesMap(dataroot=map_folder,
  File "/home/kevingal/phd/placement/lift-splat-shoot/src/tools.py", line 288, in <dictcomp>
    nusc_maps = {map_name: NuScenesMap(dataroot=map_folder,
  File "/home/kevingal/anaconda3/envs/liftsplat/lib/python3.8/site-packages/nuscenes/map_expansion/map_api.py", line 88, in __init__
    with open(self.json_fname, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kevingal/phd/placement/nuscenes/mini/maps/singapore-hollandvillage.json'
```

Cheers.

**Comment by maciej-autobon** [comment]
@Kevinpgalligan I was just curious did you manage to get around this problem?

**Comment by Kevinpgalligan** [comment]
(1) I just installed tensorboardX through pip.

(2) You can either change the default gpuid in the script or pass gpuid as a parameter.

(3) I think I had to download additional stuff from the nuScenes website. Maybe the maps are only in the full dataset? Or you download them separately?

**Comment by maciej-autobon** [comment]
Gotcha.

The (3)-rd problem is currently my last remaining problem.

Once I'll manage to get to running, I'll put down the solution here, for posterity.

**Comment by maciej-autobon** [comment]
OK, so I used the "mini" dataset, and the issue with the map file missing was resolved once I downloaded both map packs (US and Asia). Before that I had only downloaded the US part.

@Kevinpgalligan I think you can close this issue.

**Comment by Kevinpgalligan** [comment]
Ideally, this information would be added to the documentation before closing the issue, so that people don't trip up on this stuff again.

**Comment by maciej-autobon** [comment]
Yea, you're right.

I guess I'm just used to treating the Issues section as an extension of the documentation.
