### ISSUE TITLE
Training with 'vizdata'

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [nv-tlabs/lift-splat-shoot#34]
'vizdata' is ment for visualization of lidar data only, i just tried a dumb thing by assuming vizdata might be useful for detections. I was thinking it is for detections rather than segmentation. Is it possible to have training with detections alone?
Is this github works only for segmentationdata? when i try giving vizdata, it is giving the below error
    for batchi, (imgs, rots, trans, intrins, post_rots, post_trans, lid_pts, binimgs) in enumerate(trainloader):
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/anaconda3/envs/data_visual/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 80137] at entry 0 and [3, 80421] at entry 1

**Comment by VeeranjaneyuluToka** [comment]
Looks like this is invalid totally (got confused between segmentationdata and vizdata) and this github only ment for segmentation alone. Ignore this issue.
